// Shared tag -> brand-icon mapping used by project tag pills and
// experience stack pills. Keys must match the tag/stack label exactly.
export const TECH_ICONS: Record<string, string> = {
  "Next.js": "/tech-icons/mono-dark-nextjs.svg",
  React: "/tech-icons/react.svg",
  TypeScript: "/tech-icons/typescript.svg",
  Tailwind: "/tech-icons/tailwind.svg",
  "Three.js": "/tech-icons/mono-Three.js.svg",
  tldraw: "/tech-icons/mono-tldraw.svg",
  Prisma: "/tech-icons/mono-Prisma.svg",
  Bun: "/tech-icons/mono-Bun.svg",
  "Radix UI": "/tech-icons/mono-Radix UI.svg",
  Gemini: "/tech-icons/mono-Gemini.svg",
  JavaScript: "/tech-icons/javascript.svg",
  Express: "/tech-icons/mono-dark-express.svg",
  Docker: "/tech-icons/docker.svg",
  Java: "/tech-icons/java.svg",
  SQL: "/tech-icons/sql.svg",
  "C/C++": "/tech-icons/mono-C.svg",
  "HTML & CSS": "/tech-icons/mono-HTML-CSS.svg",
  Spring: "/tech-icons/mono-Spring.svg",
  "Spring Boot": "/tech-icons/mono-Spring Boot.svg",

  // Tech Stack pills
  "Node.js": "/tech-icons/nodejs.svg",
  PostgreSQL: "/tech-icons/postgresql.svg",
  MongoDB: "/tech-icons/mongodb.svg",
  Redis: "/tech-icons/redis.svg",
  Git: "/tech-icons/Git.svg",
  GitHub: "/tech-icons/mono-dark-github.svg",
  Figma: "/tech-icons/figma.svg",
  Linux: "/tech-icons/linux.svg",
  Expo: "/tech-icons/mono-dark-expo.svg",
  Django: "/tech-icons/mono-dark-django.svg",
  Zustand: "/tech-icons/mono-dark-zustand.svg",
  "TanStack Query": "/tech-icons/mono-dark-tanstack.svg",
  Postman: "/tech-icons/postman.svg",
  "shadcn/ui": "/tech-icons/mono-dark-shadcn.svg",
  Motion: "/tech-icons/mono-dark-motion.svg",
  GSAP: "/tech-icons/gsap.svg",
};
